---
fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    yumrepo_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: '>= 6.0.0'
